### ISSUE TITLE
Test step as a function

### ISSUE THREAD

**Issue by necdetterkes** [akshayp7/playwright-typescript-playwright-test#39]
Hello Akshayp, 
First of all thank you for this amazing template.

I need to implement BDD format this template, For example
Now my test cases like this

test('Create new customer and get api credentials', async ({ newIndividualCustomerPage, signInPage }) => {
    await test.step('Onboarding new individual customer', async () => {
      indOnboardingID = await newIndividualCustomerPage.newIndCustomer()
      await signInPage.gotoWebPortal()
      await signInPage.officerLogIn('midoffice')
      await midOfficerPage.customerOnboardingKYC(indOnboardingID, 'individual')
      await midOfficerPage.createCustomer(indOnboardingID)
      await signInPage.logOut()
    })
    await test.step('First time login and create password', async () => {
      await signInPage.gotoWebPortal()
      await signInPage.firstTimeLogin(indEmailId, indFirstTimeLoginPass)
      await signInPage.passwordSetup()
      await signInPage.twoFactorSetup(indEmailId)
      await signInPage.logOut()
    })
  })
  
  
  The problem is I have to duplicate some functions during create my test cases, but I want to create functions for these test steps and I want to call these steps like this
 
test('Create new customer and get api credentials', async ({ newIndividualCustomerPage, signInPage }) => {
    await functions.OnboardingNewIndividualCustomer
    await functions.FirstTimeLoginAndCreatePassword
  })
  
  
  The problem is when I want to create functions.ts file, I cannot call pages functions

**Comment by akshayp7** [comment]
Hi @necdetterkes thank you for your support and suggestion. I am looking into it and will get back to you once I find something on this query.

**Comment by akshayp7** [comment]
Hi @necdetterkes , I went through Playwright's official documentation, but I couldn't find how to create steps as function. If you want step as function you have to include cucumber library for time being. Below is the great article on that. 
https://medium.com/@manabie/how-to-use-playwright-in-cucumberjs-f8ee5b89bccc

In the mean time you can ask this question on Playwright's Slack channel. Someone from the community might be able to help you out on the same.
https://aka.ms/playwright-slack

**Comment by necdetterkes** [comment]
@akshayp7 I found this solution. 
I created Common.ts file and I create functions, these functions include test steps like this

export async function Login (emailID: string, signInPage: SignInPage) {
  await test.step(`Login `, async () => {
    await signInPage.gotoPortal()
    await signInPage.logIn(emailID)
    await signInPage.verifyLoginSuccess(emailID)
  })
}

And on the test file I call this function like this 

test('Create new non individual customer', async ({ signInPage }) => {
    customerEmail = 'necdet@yopmail.com'
    await webPortal.Login(userEmailID, signInPage)
  })
})

With this solution, I don't have to repeat lines of code.

**Comment by akshayp7** [comment]
Thank you for this solution. Is it fine to close the issue then , do you have any more inputs for my framework?
