### ISSUE TITLE
unable to run qa env

### ISSUE THREAD

**Issue by prajyot7** [akshayp7/playwright-typescript-playwright-test#57]
![image](https://github.com/akshayp7/playwright-typescript-playwright-test/assets/25434538/1159e2ba-4276-46d2-8161-cefe57b0ab01)

**Comment by akshayp7** [comment]
Hi @prajyot7 . I will have a look into this issue. Are you running this as it is or have you modified something?

**Comment by prajyot7** [comment]
Hi @akshayp7 
I direct run your code as given instructions in read me file without making any modifications

**Comment by akshayp7** [comment]
Hi , Please take the latest version of my project . I tried on my machine it is working correctly. I have attached the screenshot 
![PlaywrightTest](https://github.com/akshayp7/playwright-typescript-playwright-test/assets/78036666/d15987da-e284-4ad3-b3b6-f079e914cfb1)

**Comment by kwiatek91** [comment]
> Hi , Please take the latest version of my project . I tried on my machine it is working correctly. I have attached the screenshot ![PlaywrightTest](https://private-user-images.githubusercontent.com/78036666/294895102-d15987da-e284-4ad3-b3b6-f079e914cfb1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTA1NzMsIm5iZiI6MTcwNDg5MDI3MywicGF0aCI6Ii83ODAzNjY2Ni8yOTQ4OTUxMDItZDE1OTg3ZGEtZTI4NC00YWQzLWIzYjYtZjA3OWU5MTRjZmIxLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEyMzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzNmOTg3OGE3NzQ4MTU3MWY3ZWY4MmU0MDdlZTQ3ZDk5MTY2NmNmMTI4ZTlkMGQ2YjJkYWE4NGQ5Nzc3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyC5qtVSlPDXTgOZlYMsJiqEQn8OVrlY-e2qRCtdF1k)

i have same issue, just started with playwright and i found your freamwork looks pretty solid but also cant start 
(working on macos)

<img width="1108" alt="image" src="https://github.com/akshayp7/playwright-typescript-playwright-test/assets/11145404/7ad3e47f-e1c4-4398-936c-402d0df2bc8a">

**Comment by akshayp7** [comment]
@kwiatek91 : I just checked in my windows Machine I was able to launch it. Please try command 
npm run test --ENV="qa"

**Comment by akshayp7** [comment]
Can you also please check if other commands are working for you because the above command will run entire tests..

**Comment by kwiatek91** [comment]
> npm run test --ENV="qa"

same thing
![image](https://github.com/akshayp7/playwright-typescript-playwright-test/assets/11145404/5d236460-cab5-4e83-b88e-80833174e1dc)
also other commands:

![image](https://github.com/akshayp7/playwright-typescript-playwright-test/assets/11145404/8e433fe6-718b-401b-acd3-1c9450976076)

**Comment by akshayp7** [comment]
@prajyot7 : I have checked on Windows os. It's working on Ubuntu Linux as well I had checked. Mac I didn't get opportunity to check

**Comment by kwiatek91** [comment]
> @prajyot7 : I have checked on Windows os. It's working on Ubuntu Linux as well I had checked. Mac I didn't get opportunity to check

so this looks like system problem (project setup) on macos (other project works good, but maybe there is some problem in configuration to be honest i don't have enaught knowledge right now from TS / Playwright to find what cause the problem, but definitely it is a problem with parametrization)

**Comment by akshayp7** [comment]
Looks like the ENV supports windows os. Only can you check on how to pass environment variable in Mac . I don't have experience working with mac

**Comment by akshayp7** [comment]
For MAC i think cross-env library works just fine. I had added this in my project earlier but then later i removed cross-env package and tried using internal ENV provided by ts. If you want tou can check out my earlier commit where I have used cross-env Checkout my 1.2.0 release

https://github.com/akshayp7/playwright-typescript-playwright-test/releases/tag/v1.2.0

**Comment by akshayp7** [comment]
Did you get a change to use cross-env . Did issue get resolved

**Comment by akshayp7** [comment]
Any updates on the issue @prajyot7 @kwiatek91 ?

**Comment by Akhilesh7057** [comment]
Same issue I'm facing on Mac

**Comment by akshayp7** [comment]
@Akhilesh7057 : please try cross-env library it's with 1.2.0 release and let me know if it works. Or I had same issue while creating docker container so I defines environment variable in file itself. You can take abloom at the docker file and docker run command.

**Comment by yashlohakare-certa** [comment]
Solution for MAC-users : Before running the test execution command please run the below command 
export npm_config_ENV="qa" 
It works fine

**Comment by akshayp7** [comment]
@yashlohakare-certa thank you for your help and support. Can anyone else confirm that this solution is working for you.

**Comment by akshayp7** [comment]
Closing this issue as solve. Please reopen if you face the same even after using export npm_config_ENV="qa" command

**Comment by akshayp7** [comment]
Hi Guys. If you are using VS code please try the below suggestion on your MAC machines
