### ISSUE TITLE
Unable to run tests through VS code extension

### ISSUE THREAD

**Issue by yashlohakare-certa** [akshayp7/playwright-typescript-playwright-test#61]
Is there any way to run tests using vs code playwright test runner extension? As of now it just shows everything as empty and not able to recognise the tests.

**Comment by akshayp7** [comment]
I haven't tried with this vs code extension. Let me check on that

**Comment by akshayp7** [comment]
1. I tried changing name to test cases from .test.ts to spec.ts, still its not working.
2. Tried proving tests in "testdir" under playwright.config.ts taht didnt work.
3. Looks like something to do with the way we configure env variable.

**Comment by akshayp7** [comment]
Hi I had posted in Playwright community and got the below answer. Please refer to this. I was planning that the user must be able to pass the value from command line itself. So might not be able to implement the changes. Please revert if this solution works for you.

https://github.com/microsoft/playwright/issues/29950

**Comment by yashlohakare-certa** [comment]
Yes Akshay, I've tweaked the current framework to pass on env variables in form on json instead of command line and it works fine now. So marking it as close!
